name: Scrape Talk Locations

on:
  push:
    paths:
      - '_pages/cv.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install jupyter pandas requests beautifulsoup4 geopy  # Add other dependencies as needed
        pip install getorg --upgrade

    - name: Run CV Update Script
      run: |
        python scripts/cv_markdown_to_json.py --input _pages/cv.md --output _data/cv.json --config _config.yml

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated update of CV data" || echo "No changes to commit"
        git push
